### ISSUE TITLE
TeradiciClient fails

### ISSUE THREAD

**Issue by paulc-us** [autopkg/foigus-recipes#104]
Error in local.munki.TeradiciClient: Processor: PkgCreator: Error: chown path Applications/PCoIPClient.app/Contents/MacOS/TeradiciUsbRedirection does not exist

Looks like that path doesn't exist in the newest version.

**Comment by foigus** [comment]
Should be fixed by https://github.com/autopkg/foigus-recipes/commit/f5bec53f506442f8a05b44523a00f817b852cb90.
