### ISSUE TITLE
Voila is now Capto

### ISSUE THREAD

**Issue by homebysix** [autopkg/foigus-recipes#12]
Product page:
http://www.globaldelight.com/capto/

Blog where they introduce Capto:
http://www.globaldelight.com/blog/introducing-capto-a-powerful-screen-capture-app-with-a-video-editor/

Not sure whether this warrants a whole new set of recipes or just a new NAME. I'll leave that up to you.

**Comment by foigus** [comment]
Added Capto recipes.
