### ISSUE TITLE
Magic Bullet Download failing

### ISSUE THREAD

**Issue by markkenny** [autopkg/foigus-recipes#125]
Looks like MAXON have removed Magic Bullet? https://www.maxon.net/en/downloads

I don't think editing your download recipe can fix this ;-)

`Error in com.mycom.jamf.autopkg-MagicBulletSuite: Processor: URLTextSearcher: Error: No match found on URL: https://www.maxon.net/_nuxt/static/1694759311/en/downloads/payload.js`

**Comment by foigus** [comment]
It's under the "Red Giant" heading at https://www.maxon.net/en/downloads .

**Comment by markkenny** [comment]
Doh, and it's behind a login now?
