### ISSUE TITLE
"Maxon App Installer code signature verification failed"

### ISSUE THREAD

**Issue by miawri** [autopkg/foigus-recipes#130]
The Maxon App installer Bundle ID has now changed to "net.maxon.maxonapp.installer" from "com.redgiant.Red-Giant-Service-Installer" so the MaxonApp.download.recipe needs updating.

`<dict>
	<key>Arguments</key>
	<dict>
		<key>input_path</key>
		<string>%pathname%/Maxon App Installer.app</string>
		<key>requirement</key>
		<string>identifier "net.maxon.maxonapp.installer" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "4ZY22YGXQG"</string>
	</dict>
	<key>Processor</key>
	<string>CodeSignatureVerifier</string>
</dict>`

**Comment by foigus** [comment]
[Done](https://github.com/autopkg/foigus-recipes/commit/79d13d3a1537e1277ccc18291ee23430d4c0bd70).
