### ISSUE TITLE
Maxon App pkg installation script changed

### ISSUE THREAD

**Issue by adamlazar1** [autopkg/foigus-recipes#132]
Current recipe is calling this install script:
# Install Maxon App Installer using the script from the resources directory
"${install_dir}/Maxon App Installer.app/Contents/Scripts/install.sh"</string>

New location and script is: /Maxon App Installer.app/Contents/MacOS/installbuilder.sh

**Comment by foigus** [comment]
[Updated](https://github.com/autopkg/foigus-recipes/commit/6cfdc203500bf88f3049314b7460b48c5a7a084f).

**Comment by adamlazar1** [comment]
> I think this script should also be called with `--unattendedmodeui none` to install silently. @foigus

Yea, running into the same issue here now. They updated their documentation on Friday.
https://support.maxon.net/hc/en-us/articles/4687177301788-Running-Scripted-Installers

**Comment by foigus** [comment]
Updated [here](https://github.com/autopkg/foigus-recipes/commit/67be9ae76a339c25652bbb265b2936c1869a232c).  Please test and let me know your results.

Please note it's easier to "see" issues if they're filed "new" rather than commenting with an issue that's been closed for two weeks.
