### ISSUE TITLE
Maxon Trapode suite download failed

### ISSUE THREAD

**Issue by markkenny** [autopkg/foigus-recipes#138]
My guess is Maxon are messing around with the files on the site again. Is the regex case sensitive?

https:\/\/mx-app-blob-prod\.maxon\.net\/mx-package-production\/installer\/macos\/redgiant\/trapcode\/releases\/[\d\.]+\/TrapcodeSuite-[\d\.]+_[Mm]ac\.zip

The URL...

https://mx-app-blob-prod.maxon.net/mx-package-production/installer/macos/redgiant/trapcode/releases/2024.1.0/TrapcodeSuite-2024.1.0_mac.zip

https://github.com/autopkg/foigus-recipes/blob/master/Maxon/TrapcodeSuite.download.recipe

The following recipes failed:
    Maxon-TrapcodeSuite.jamf.recipe.yaml
        Error in com.mygroup.jamf.autopkg-maxon-trapcodesuite: Processor: URLTextSearcher: Error: No match found on URL: https://www.maxon.net/en/downloads

**Comment by foigus** [comment]
https://github.com/autopkg/foigus-recipes/commit/993d32a342f2f96ac58229ddd82821cc48f6ba62
