### ISSUE TITLE
MicrosoftRemoteDesktop.munki.recipe

### ISSUE THREAD

**Issue by kevinmcox** [autopkg/foigus-recipes#152]
Microsoft has renamed "Remote Desktop" to "Windows App" and it looks like today is the day that the parent recipe has started pulling down the new package.

This recipe will need an update in several places.

**Comment by kevinmcox** [comment]
Rich is going to deprecate the parent recipe this one uses:
https://github.com/autopkg/rtrouton-recipes/issues/195

**Comment by foigus** [comment]
Accepted https://github.com/autopkg/foigus-recipes/pull/153.
