### ISSUE TITLE
EFI/GenericFieryFD50.download.recipe Mismatch in authority names

### ISSUE THREAD

**Issue by gregneagle** [autopkg/foigus-recipes#19]
Packages downloaded from EFI as of April 6, 2017 may have a different Developer ID Installer cert:

$ pkgutil --check-signature /Volumes/Fiery\ Printer\ Driver/Fiery\ Printer\ Driver.pkg 
Package "Fiery Printer Driver.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: EFI Inc (82PCFB3NFC)
       SHA1 fingerprint: AE 40 A8 91 52 57 6C 90 AF 9B 7C 2B 32 A9 1B 31 B7 B7 86 97
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60

**Comment by foigus** [comment]
Addressed with https://github.com/autopkg/foigus-recipes/commit/f492596f72e074468d4cfb77b5e3735d205efe00.
