### ISSUE TITLE
AndroidStudio SEARCH_PATTERN error

### ISSUE THREAD

**Issue by jelockwood** [autopkg/foigus-recipes#53]
@foigus 
Please see this issue on the parent AndroidStudio download recipe.

https://github.com/autopkg/novaksam-recipes/issues/53

It seems your AndroidStudio munki recipe has an ovveride of the SEARCH_PATTERN and hence is overriding the 'fix' incorporated in the parent download recipe. As a result when I run your munki recipe it fails.

The fix was as per https://github.com/autopkg/novaksam-recipes/pull/54/commits/2191473ecc3a000841518435811af26f74b4c18f

**Comment by foigus** [comment]
I believe this was fixed by merging [this recent PR](https://github.com/autopkg/foigus-recipes/commit/f372734dc8c3b9581c32913a2a479012fd4e86b5#diff-11d2ad0a806b2abd1439a79688d59a3a)

**Comment by foigus** [comment]
Note overrides of AndroidStudio.munki might need to be updated, or have the `VERSION_SEARCH_PATTERN` and `VERSION_SEARCH_URL` Input variables removed entirely, deferring to the ones in my recipes.

**Comment by jelockwood** [comment]
I did some more checking and it was my fault - a misunderstanding of overrides. I am closing this issue.
