### ISSUE TITLE
Ecamm CallRecorderforSkype download

### ISSUE THREAD

**Issue by vmiller** [autopkg/foigus-recipes#54]
This recipe started failing for me, and it looks like the download url has changed changed from cdn.ecamm.com to www.ecamm.com

I tried fixing the url in the recipe, but it doesn't download a working zip file.  I see there is a DMG download option of Ecamm's download site, but if I try to modify the recipe to download the dmg I do not get a working disk image file.  

The same URLs generated by the recipe work when I paste them into a browser, so I'm not sure what I am missing...

**Comment by foigus** [comment]
The file that's downloaded includes the statement:

_Call Recorder for Skype is software that needs to be installed on a **Mac**
(This doesn't look like a Mac.)
Continue to download it anyway?_

Lemme see what I can do.

**Comment by foigus** [comment]
Should be fixed by https://github.com/autopkg/foigus-recipes/commit/310660f4e62dd7138ac449b70cd95c2a9ae9320d.
