### ISSUE TITLE
Sketch recipe downloads incorrect old version instead of current one

### ISSUE THREAD

**Issue by jelockwood** [autopkg/foigus-recipes#56]
I had it brought to my attention that our Munki aka Managed Software Centre was not providing the latest version of Sketch.

I checked and currently Munki has version 65.1.95501 whereas the latest is actually 66.1.97063.

I use AutoPkg and AutoPkg had not reported any error with the Sketch recipe and clearly had not added the new 66.1 version.

I cleared the cache for the Sketch recipe and ran it again and it still downloads 65.1.95501 it therefore looks like there is a problem with the download recipe.

A quick check shows your download recipe is using the Sparkle mechanism. Perhaps the Sketch authors have stopped using this or updated the settings.

Can you look in to this please?

**Comment by jelockwood** [comment]
Ah! Maybe the issue is OS versions.

The Mac I run AutoPkg on is still running under High Sierra aka 10.13.6. It looks like the Sketch version 66.9 requires a newer operating system to run. Since I have no intention to run Sketch on the AutoPkg hosting Mac this did not occur to me.

Would this be the problem? It could be looking for the newest version of Sketch compatible with High Sierra.

Is there anyway to workaround this other than upgrading the Mac running AutoPkg? It is running the latest AutoPkg.

**Comment by foigus** [comment]
Bohemian Coding's servers don't consider the parent OS's version when checking for updates.  The only thing Bohemian Coding sees is SparkleUpdateInfoProvider running the equivalent to the command:

`curl -L https://www.sketchapp.com/appcast3.xml -A "Sketch/3.3.2 Sparkle/e759c10"`

Currently I'm seeing version 66 reported through the Sparkle feed:

```
$ curl -L https://www.sketchapp.com/appcast3.xml -A "Sketch/3.3.2 Sparkle/e759c10"
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
  <channel>
    <title>Sketch</title>
    <link>https://sketchapp.com/</link>
    <description>Sparkle feed for Sketch</description>
    <docs>http://blogs.law.harvard.edu/tech/rss</docs>
    <language>en</language>
    <atom:link href="https://download.sketchapp.com/sketch-versions.xml" rel="self" type="application/rss+xml"/>

    <item>
      <title>Sketch 66</title>
      <description>The final build of Sketch 66</description>
      <pubDate>19 May 2020</pubDate>
      <sketchSupportDate>19 May 2020</sketchSupportDate>
      <sparkle:minimumSystemVersion>10.14.4</sparkle:minimumSystemVersion>
      <sparkle:releaseNotesLink>https://download.sketchapp.com/sketch-66.html</sparkle:releaseNotesLink>
      <enclosure url="https://download.sketchapp.com/sketch-66-97063.zip" length="56419373" type="application/zip" sparkle:version="97063" sparkle:shortVersionString="66" sparkle:edSignature="Nlnhq1qkl55/dIhN/ztgHXldWvlc/PRW97HtIiCGgINdEag4XT4fRYuc+GmH+U6ck10aX082W4qsUCj9boA+BA=="/>
      <guid isPermaLink="false">9952252c-b6e3-44e4-aed5-9ada33f57fb8</guid>
    </item>
```

Bohemian Coding has in the past (unintentionally or intentionally) [not always offered the latest version through the Sparkle feed](https://macadmins.slack.com/archives/C056155B4/p1581949308426700).  If that's because they're only releasing it to a percentage of auto-updating Sketch installations or due to an infrastructure difficulty where the same Sparkle feed isn't being sent to all clients, I'm not sure.  But at this point it does not appear to be anything related to AutoPkg or the recipe.

**Comment by jelockwood** [comment]
Thank you for the fast response. I tried the curl command on both my AutoPkg machine running High Sierra and my own work laptop running Mojave. Both at least whilst in the same office returned the same results with the top newest section of the results being as follows.

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
  <channel>
    <title>Sketch</title>
    <link>https://sketchapp.com/</link>
    <description>Sparkle feed for Sketch</description>
    <docs>http://blogs.law.harvard.edu/tech/rss</docs>
    <language>en</language>
    <atom:link href="https://download.sketchapp.com/sketch-versions.xml" rel="self" type="application/rss+xml"/>

    <item>
      <title>Sketch 65.1</title>
      <description>The final build of Sketch 65.1</description>
      <pubDate>04 May 2020</pubDate>
      <sketchSupportDate>28 April 2020</sketchSupportDate>
      <sparkle:minimumSystemVersion>10.14.4</sparkle:minimumSystemVersion>
      <sparkle:releaseNotesLink>https://download.sketchapp.com/sketch-65.1.html</sparkle:releaseNotesLink>
      <enclosure url="https://download.sketchapp.com/sketch-65.1-95501.zip" length="56111716" type="application/zip" sparkle:version="95501" sparkle:shortVersionString="65.1" sparkle:edSignature="Nmv9fUWp1Jg/Kaeves1M0YLhHCc7/+P+Sw84gAE7u9oqnN4WVWHTbUhlpr/9mO7V0GfisGgA2NcQAPWxFsZHDw=="/>
      <guid isPermaLink="false">952941fb-b3e4-4e06-b300-9910eb92983c</guid>
    </item>
```

As you can see the top most result presumably will always be the newest in their feed and it is 65.1 and I checked the full list the command returned and it did not include 66.1.

It therefore firstly confirms it is not an OS issue and yes it would seem to indicate they have not let me see the new version. I will close the issue since it seems their fault.

Just VPN connected to my home and tried the same curl command there and it shows 66.1.
