### ISSUE TITLE
URLTextSearcher Pattern no longer correct

### ISSUE THREAD

**Issue by richard-datajar** [autopkg/foigus-recipes#57]
The download page returns this xml

```
<VersionNum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://tempuri.org/">
<NewVersionAvailable>True</NewVersionAvailable>
<AvailableVersion>13.1.0.172</AvailableVersion>
<DownloadURL>https://account.captureone.com/en/account/download</DownloadURL>
<ReleaseNoteURL>http://www.captureone.com</ReleaseNoteURL>
<PaidVersion>True</PaidVersion>
</VersionNum>

```

The pattern match no longer finds the correct version. 

`<string>&lt;AvailableVersion&gt;(%MAJOR_VERSION%[\.\d]*)\.[\d]*&lt;\/AvailableVersion&gt;</string>
`

Set MAJOR_VERSION to 20 , which is required for the app name, does not work with the pattern match any more.

**Comment by foigus** [comment]
Seems a bit of work with Charles as well as poking around Phase One's webpages is necessary to see if there's still a publicly-available download of Capture One.

**Comment by richard-datajar** [comment]
The download is still public. This is the current url.

https://downloads.phaseone.com/374dd05f-e8c7-499d-a703-9a7dca20d5b7/International/CaptureOne20.Mac.13.1.0.dmg

Because MAJOR_VERSION is used for both the app name and the version in the pattern search it fails.

**Comment by foigus** [comment]
Apparently Phase One has changed something, because this was working up until a few days ago (I run nearly all my recipes nightly and I had seen the failures as well, however I generally don't jump in until something fails for a few days straight).

This (unfortunately) is due to the bifurcation of the actual software version and the marketing version.  I'll see what I can do.

**Comment by richard-datajar** [comment]
Cheers. I know, its a pain with the software and marketing version.

**Comment by foigus** [comment]
Check the current commits to master (namely https://github.com/autopkg/foigus-recipes/commit/542477c045efbe0197e52aadaf43362f62589aec and https://github.com/autopkg/foigus-recipes/commit/448308694c4fc3288310be5c1511fe47404f7636 ).

Note you'll need to edit your override with some new/different Input.

**Comment by richard-datajar** [comment]
All looks fab. Thank you.
