### ISSUE TITLE
ColorMunki Photo has been replaced with a new app, i1Studio

### ISSUE THREAD

**Issue by flammable** [autopkg/foigus-recipes#60]
The ColorMunki Photo recipes can probably be deprecated, as the app is 32-bit and has been replaced:

https://xritephoto.com/ph_product_overview.aspx?action=support&id=1115

At least the new app doesn't have "Munki" in the name 😆

It looks like [this happened a year ago](https://xritephoto.com/ph_product_overview.aspx?ID=2458&Action=Support&SupportID=5932&catid=157), but it wasn't on my radar.

**Comment by foigus** [comment]
Deprecated--thanks for letting me know!

https://github.com/autopkg/foigus-recipes/commit/539f3bf4e5ad85897fda58b2de4a207913efde34
