### ISSUE TITLE
CaptureOne Download recipe failing

### ISSUE THREAD

**Issue by neilmartin83** [autopkg/foigus-recipes#63]
Heya,

It looks like something has changed with the endpoint used for URLTextSearcher - might be a temporary error on their side. I had a quick look at their website but they put the trial download behind a login wall, so couldn't glean too much, sorry.

![image](https://user-images.githubusercontent.com/10920581/96878904-44067300-1473-11eb-86da-f4292d9045bd.png)

**Comment by foigus** [comment]
Given this is the same URL that Capture One itself retrieves when checking for updates, going to wait patiently and see if Phase One can fix this themselves.

**Comment by foigus** [comment]
@neilmartin83 You still seeing issues with this?

**Comment by neilmartin83** [comment]
@foigus looks to be working again now - problem was at their end!

I'll close this - thank you.
