### ISSUE TITLE
Call Recorder for Skype not showing up

### ISSUE THREAD

**Issue by floriangeyer** [autopkg/foigus-recipes#66]
I’m using Munki to deploy Call Recorder for Skype (v3.0.12). The installation completes successfully but the Call Recorder window doesn’t show up when opening Skype. I’m on MacOS 10.15.7 and the latest Skype 8.67.0.91

**Comment by foigus** [comment]
Should be fixed by this commit: https://github.com/autopkg/foigus-recipes/commit/c33eb8054fcc49e0af68c61cacf8ea4ccc94853a

Please read and understand the steps an AutoPkg user would need to perform to actually cause the change to take effect in their packages.
