### ISSUE TITLE
MagicBulletSuite.download: No matching filename found

### ISSUE THREAD

**Issue by floriangeyer** [autopkg/foigus-recipes#69]
I get the following error when running autopkg on MagicBulletSuite.munki:

`The following recipes failed:
    MagicBulletSuite.download.recipe
        Error in local.download.MagicBulletSuite: Processor: FileFinder: Error: No matching filename found`

**Comment by foigus** [comment]
Fixed by this commit.

https://github.com/autopkg/foigus-recipes/commit/eb13be4dca07f41093c7063246c9466a55e369cb
