### ISSUE TITLE
URLDownloader error with HP/HPEasyAdmin.download.recipe

### ISSUE THREAD

**Issue by Balthamos** [autopkg/foigus-recipes#72]
Hi! I don't know if this could just be a temporary issue as it's only been occurring for a few days, but recently any time this recipe is ran (or more specifically, the Munki child-recipe), it fails with the following error:

`Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'ftp://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Applications/HP_Easy_Admin.app.zip', '--fail', '--output', '/AutoPkg/Cache/local.munki.HPEasyAdmin/downloads/tmpzz9h4s_e']' returned non-zero exit status 56. Failed.`

On a whim, I tried changing the `DOWNLOAD_URL` in my override from an ftp:// url to an https:// url (`https://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Applications/HP_Easy_Admin.app.zip`) and surprisingly that seems to have fixed the issue; it's now successfully both downloading and being imported into Munki.

**Comment by foigus** [comment]
I also am seeing this during my nightly runs of my own AutoPkg recipes, including multiple runs of the `curl` command by hand:

`/usr/bin/curl -vvvvv --silent --show-error --no-buffer --dump-header - --speed-time 30 --location --url ftp://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Applications/HP_Easy_Admin.app.zip --fail --output out.zip`

I've also seen browser-based failures (with an error that the server isn't reachable).  Notably there is [discussion in MacAdmins Slack](https://macadmins.slack.com/archives/C069L8WFR/p1612970421097900) about HP Easy Admin itself having issues.

I'll let the issue go for a couple days and see if HP resolves it, and then I'll give the https URL you suggested a shot--thanks!

**Comment by foigus** [comment]
Appears to be working now.
