### ISSUE TITLE
CiscoWebexAudioDriver download link 404ing

### ISSUE THREAD

**Issue by poundbangbash** [autopkg/foigus-recipes#77]
The download link seems to no longer be valid.  
https://github.com/autopkg/foigus-recipes/blob/master/Cisco/CiscoWebexAudioDriver.download.recipe#L17

Attempting to curl that URL directly results in a 404 returned.
``` 
% curl -I https://www.cisco.com/c/dam/en/us/td/docs/collaboration/webex_centers/Collaboration-Help/TS-Help-Portal-Support-Utilities/CiscoAudioDeviceInstall.zip
HTTP/1.1 404 Not Found
```

**Comment by foigus** [comment]
Fixed by https://github.com/autopkg/foigus-recipes/commit/6475a2bcf944b5cfabef86a8995ded1541d3065d and the followup https://github.com/autopkg/foigus-recipes/commit/a38f8a5dd70359f5f07cf5800353f8b09d80f419.
