### ISSUE TITLE
ColorNavigator7.munki Install Fail

### ISSUE THREAD

**Issue by TekTekkers** [autopkg/foigus-recipes#79]
Hi

There seems to be an error with this recipe.

The following recipes failed:
    /Users/admin/Library/AutoPkg/RecipeOverrides/ColorNavigator7.munki.recipe
        Error in local.munki.ColorNavigator7: Processor: Copier: Error: Error processing path '/Users/admin/Library/AutoPkg/RecipeOverrides/Reference Scripts ColorNavigator7/Fixed Script/postinstall' with glob. 

Tried updating trust info, autopkg -vv, updated the autopkg repo, still getting the same error

**Comment by foigus** [comment]
Please override `POSTINSTALL_SCRIPT_PATH`.

https://github.com/autopkg/foigus-recipes/blob/master/EIZO/ColorNavigator7.pkg.recipe#L9

**Comment by TekTekkers** [comment]
Hi Pal

Thanks for that.
First time im doing that, how would I do this?
Apologies 

Thanks
