### ISSUE TITLE
plist error for TeradiciClientBeta

### ISSUE THREAD

**Issue by eshirk** [autopkg/foigus-recipes#81]
Our CI is generating the following:

WARNING: plist error for /Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes/Teradici/TeradiciClientBeta.pkg.recipe: not well-formed (invalid token): line 10, column 1

**Comment by foigus** [comment]
Any more information?  I can vet `plutil -lint` passes against `TeradiciClientBeta.pkg.recipe` and the recipe runs to completion for me.

**Comment by eshirk** [comment]
All three TeradiciClientBeta recipes were failing plutil -lint checks for me, but an attempted repo-update shows issues on our end. Sorry about the noise!
