### ISSUE TITLE
Checksum error with WoodwingStudioInDesignCC2020.munki.recipe and latest Plugin version 15.2.0 Build 49

### ISSUE THREAD

**Issue by anacreonza** [autopkg/foigus-recipes#82]
When attempting to run the WoodwingStudioInDesignCC2020.munki recipe against the latest version of the plugins from Woodwing autopkg gives a checksum error. It seems to check the MD5 checksums for the uninstaller binaries and fails due to them being different from what is expected. Note that once the checksum verification processor is removed from the original recipe and a new override is created the new plugins import fine and appear to install normally onto clients.

autopkg run WoodwingStudioInDesignCC2020.munki.recipe -p ~/Downloads/WoodWing_Studio_for_InDesign_and_InCopy_2020_v15.2.0_Build49.dmg -vvv
Processing WoodwingStudioInDesignCC2020.munki.recipe...
{'AUTOPKG_VERSION': '2.1',
 'MUNKI_REPO': '/Shared/munkirepo',
 'MUNKI_REPO_SUBDIR': 'plugins/woodwing',
 'NAME': 'WoodwingStudioInDesignCC2020',
 'PARENT_RECIPES': ['/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes/WoodWing/WoodwingStudioInDesignCC2020.munki.recipe'],
 'PKG': '/Users/srvadmin/Downloads/WoodWing_Studio_for_InDesign_and_InCopy_2020_v15.2.0_Build49.dmg',
 'RECIPE_CACHE_DIR': '/Users/srvadmin/Library/AutoPkg/Cache/local.munki.WoodwingStudioInDesignCC2020',
 'RECIPE_DIR': '/Users/srvadmin/Library/AutoPkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/srvadmin/Library/AutoPkg/RecipeOverrides/WoodwingStudioInDesignCC2020.munki.recipe',
 'RECIPE_REPOS': {'/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.adobe-ccp-recipes': {'URL': 'https://github.com/autopkg/adobe-ccp-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes': {'URL': 'https://github.com/autopkg/apettinen-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes': {'URL': 'https://github.com/autopkg/bochoven-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dankeller-recipes': {'URL': 'https://github.com/autopkg/dankeller-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.derak-recipes': {'URL': 'https://github.com/autopkg/derak-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes': {'URL': 'https://github.com/autopkg/foigus-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes': {'URL': 'https://github.com/autopkg/keeleysam-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes': {'URL': 'https://github.com/autopkg/killahquam-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes': {'URL': 'https://github.com/autopkg/nstrauss-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes'},
                  '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes': {'URL': 'https://github.com/autopkg/scriptingosx-recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.adobe-ccp-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.derak-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dankeller-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes',
                        '/Users/srvadmin/Library/AutoPkg/RecipeOverrides'],
 'pkginfo': {'Comment': 'Choices installer_choice_1 (Woodwing Studio InDesign '
                        '2020), installer_choice_2 (Woodwing Studio InCopy '
                        '2020)',
             'blocking_applications': ['Adobe InDesign 2020'],
             'catalogs': ['testing'],
             'category': 'Plugins',
             'description': 'Woodwing Studio plugins for InDesign 2020.',
             'developer': 'Woodwing',
             'display_name': 'Woodwing Studio InDesign 2020',
             'installer_choices_xml': [{'attributeSetting': 1,
                                        'choiceAttribute': 'selected',
                                        'choiceIdentifier': 'installer_choice_1'}],
             'name': 'WoodwingStudioInDesignCC2020',
             'requires': ['InDesignCC2020'],
             'unattended_install': True,
             'unattended_uninstall': True},
 'verbose': 3}
PackageRequired
{'Input': {}}
{'Output': {}}
FlatPkgUnpacker
{'Input': {'destination_path': '/Users/srvadmin/Library/AutoPkg/Cache/local.munki.WoodwingStudioInDesignCC2020/unpack',
           'flat_pkg_path': '/Users/srvadmin/Downloads/WoodWing_Studio_for_InDesign_and_InCopy_2020_v15.2.0_Build49.dmg/WoodWing_Studio_for_InDesign_and_InCopy_2020_v*.pkg',
           'purge_destination': True}}
FlatPkgUnpacker: Mounted disk image /Users/srvadmin/Downloads/WoodWing_Studio_for_InDesign_and_InCopy_2020_v15.2.0_Build49.dmg
FlatPkgUnpacker: Unpacked /private/tmp/dmg.dfkL07/WoodWing_Studio_for_InDesign_and_InCopy_2020_v15.2.0_Build49.pkg to /Users/srvadmin/Library/AutoPkg/Cache/local.munki.WoodwingStudioInDesignCC2020/unpack
{'Output': {}}
io.github.hjuutilainen.SharedProcessors/ChecksumVerifier
{'Input': {'algorithm': 'MD5',
           'checksum': 'dc1711abadbf89696b49ea5b940ba549',
           'pathname': '/Users/srvadmin/Library/AutoPkg/Cache/local.munki.WoodwingStudioInDesignCC2020/unpack/payload.pkg/Scripts/Uninstall '
                       'WoodWing Studio for InDesign and InCopy '
                       '2020.app/Contents/MacOS/Uninstall WoodWing Studio for '
                       'InDesign and InCopy 2020'}}
ChecksumVerifier: Calculating MD5 checksum for /Users/srvadmin/Library/AutoPkg/Cache/local.munki.WoodwingStudioInDesignCC2020/unpack/payload.pkg/Scripts/Uninstall WoodWing Studio for InDesign and InCopy 2020.app/Contents/MacOS/Uninstall WoodWing Studio for InDesign and InCopy 2020
ChecksumVerifier: Calculated checksum: 94044cb774d8f59525267e9be6d7c7ad
ChecksumVerifier: Expected checksum:   dc1711abadbf89696b49ea5b940ba549
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 483, in process
    self.main()
  File "/Users/srvadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes/SharedProcessors/ChecksumVerifier.py", line 84, in main
    raise ProcessorError("Error: Calculated checksum does not match expected checksum")
autopkglib.ProcessorError: Error: Calculated checksum does not match expected checksum
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
Error: Calculated checksum does not match expected checksum
Failed.
Receipt written to /Users/srvadmin/Library/AutoPkg/Cache/local.munki.WoodwingStudioInDesignCC2020/receipts/WoodwingStudioInDesignCC2020.munki-receipt-20210623-133725.plist

The following recipes failed:
    WoodwingStudioInDesignCC2020.munki.recipe
        Error in local.munki.WoodwingStudioInDesignCC2020: Processor: io.github.hjuutilainen.SharedProcessors/ChecksumVerifier: Error: Error: Calculated checksum does not match expected checksum

Nothing downloaded, packaged or imported.

**Comment by foigus** [comment]
Should be fixed by:

- https://github.com/autopkg/foigus-recipes/commit/ae874fd15e94b93830e298e29aef9c5e03a095a2
- https://github.com/autopkg/foigus-recipes/commit/97e487e7ab09031bd80ba72ee4bc07509e60a90d
- https://github.com/autopkg/foigus-recipes/commit/c75d88da8379719d87d06118d617148f7b41d987
