### ISSUE TITLE
TeradiciClientBeta.pkg.recipe: not well-formed (invalid token): line 10, column 1

### ISSUE THREAD

**Issue by MiqViq** [autopkg/foigus-recipes#84]
There seems to be an issue with this:

WARNING: plist error for /Users/thisuser/Library/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes/Teradici/TeradiciClientBeta.pkg.recipe: not well-formed (invalid token): line 10, column 1

This jumps up when rebuilding trust with my recipes. Did not happen before.

**Comment by foigus** [comment]
Remove and re-add my repo.

**Comment by MiqViq** [comment]
Removing and re-adding your repo helped, thanks!
