### ISSUE TITLE
Invision Craft Manager needs additional MunkiInstallsItems

### ISSUE THREAD

**Issue by opus-nbo** [autopkg/foigus-recipes#90]
CFBundleShortVersionString does not suffice as the CFBundleVersion is also used by the developers. 

Version in my Munki repo: `1.0.118 305`
Version available through Sparkle feed: `1.0.118 307`

Issues: 

- MunkiImporter does not import the new item
- Additional MunkiInstallsItems needed to account for the CFBundleVersion (currently `307`)

**Comment by foigus** [comment]
From what I understand, `MunkiImporter` doesn't dive as deep as `munkiimport` and considers items with matching `CFBundleShortVersionString` (e.g. that only differ by `CFBundleVersion`) to be identical.  Although adding an additional `MunkiInstallsItem` would allow the differing `CFBundleVersion` to be distinguished by Munki clients, it doesn't address the underlying difficulty with getting `MunkiImporter` to import the new release in the first place.

**Comment by foigus** [comment]
Could you reach out to Invision and see what the intent is with a newer release that retains the same `CFBundleShortVersionString`?  I've had the recipes up in some form for nearly five years and haven't seen an issue with the releases only distinguished by `CFBundleShortVersionString` so I'm curious what the need is for a revision where the developer hasn't seen fit to set a new `CFBundleShortVersionString`.

**Comment by opus-nbo** [comment]
I just opened a ticket with my Invision account. I will keep you updated.

**Comment by opus-nbo** [comment]
Response from Invision:

Monika R. (InVision)
Jan 24, 2022, 2:56 EST

> thanks so much for your feedback. I can confirm that this is already on our engineer's radar and they will be addressing it in the next update of Craft, which we're hoping to ship at some point this week.

> Apologies for any frustration this has caused and please let me know if you've got any follow up questions.

**Comment by foigus** [comment]
Given the developer appears to view this as a bug/error, can this issue be closed?

**Comment by opus-nbo** [comment]
I think the issue can be closed. Hopefully the next release has correct versioning information.

**Comment by foigus** [comment]
Looks like version Craft Manager 1.0.119 was released overnight--take a look.

**Comment by opus-nbo** [comment]
Autopkg downloaded the App and it was also imported into Munki correctly. Version is now in fact 1.0.119. So this issue can be closed. Hopefully Invision devs don't do that again.
