### ISSUE TITLE
Sketch download recipe

### ISSUE THREAD

**Issue by opus-nbo** [autopkg/foigus-recipes#91]
@foigus I noticed that v83 of Sketch is not available in the Appcast XML @ https://www.sketch.com/appcast3.xml so I contacted Support. 

Here's their answer:

> Thanks for contacting support. Apologies for the issues you are having with the AppCast XML file.
> 
> The issue with the XML file seems to be one of the cache. The team has confirmed that it might take up to a week for the appcast3.xml file to update. That is by design and the team has been notified of this.
>
>You can alternatively use this one https://download.sketch.com/sketch-versions.xml which is up to date and it appears to be updated, as soon as we release a new version.

Can you change the XML URL in the recipe? Thanks!

**Comment by foigus** [comment]
Done. https://github.com/autopkg/foigus-recipes/commit/295a4c71d50c6370e357d09a9858169f7ff82b3b
